---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev1-prime
  labels:
    app: dev1-prime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev1-prime
  template:
    metadata:
      labels:
        app: dev1-prime
    spec:
      containers:
      - name: dev1-prime
        image: 283670584284.dkr.ecr.ap-south-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
