---
apiVersion: v1
kind: Service
metadata:
  name: dev1-prime
  labels:
    app: dev1-prime
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: dev1-prime
  type: LoadBalancer
...
